"""Word report generation using tesorotools render.

Builds a Word document that mirrors the structure of the
original hogares report: title, chart sections organized
in rows of 1-2 images each, with titles and source notes.

Charts are referenced by ID (matching the PNG filenames
generated by ``src.charts``).  Missing charts are skipped
gracefully so the report can be generated with partial
data.
"""

import logging
from pathlib import Path
from typing import Any

import yaml
from docx import Document

from tesorotools.render import (  # pyright: ignore[reportMissingTypeStubs]
    Image,
    Images,
    Report,
    Section,
    Text,
    Title,
)

logger = logging.getLogger(__name__)


# ----------------------------------------------------------
# Report layout definition
# ----------------------------------------------------------

# Each row is a dict with:
#   charts: list of chart IDs (1 or 2 per row)
#   source: source attribution text
# Title and subtitle come from charts.yaml.

_SECTION_CUENTAS_FINANCIERAS: list[dict[str, Any]] = [
    {
        "charts": ["cap_nec_financiacion", "ahorro_bruto"],
        "source": "Fuente: INE y Banco de Espana",
    },
    {
        "charts": ["vna_componentes", "vnp_componentes"],
        "source": "Fuente: Banco de Espana",
    },
    {
        "charts": ["activos_stock", "activos_composicion"],
        "source": "Fuente: Banco de Espana",
    },
    {
        "charts": ["riqueza_neta", "deuda_pib"],
        "source": "Fuente: Banco de Espana",
    },
    {
        "charts": ["deuda_hogares_yoy"],
        "source": "Fuente: Banco de Espana",
    },
]

_SECTION_CREDITO: list[dict[str, Any]] = [
    {
        "charts": ["stock_credito_yoy", "flujos_credito"],
        "source": "Fuente: Banco de Espana",
    },
    {
        "charts": ["renegociaciones"],
        "source": "Fuente: Banco de Espana",
    },
]

_SECTION_TIPOS: list[dict[str, Any]] = [
    {
        "charts": ["ti_stock", "tedr_flujos"],
        "source": "Fuente: Banco de Espana",
    },
    {
        "charts": ["tedr_vivienda_tipo"],
        "source": "Fuente: Banco de Espana",
    },
    {
        "charts": ["tedr_renegociaciones"],
        "source": "Fuente: Banco de Espana",
    },
]


def _load_chart_meta(
    config_path: Path,
) -> dict[str, dict[str, str]]:
    """Load chart titles/subtitles from charts.yaml."""
    with open(config_path, encoding="utf-8") as f:
        raw = yaml.safe_load(f)
    meta: dict[str, dict[str, str]] = {}
    for cid, cfg in raw["charts"].items():
        meta[cid] = {
            "title": cfg.get("title", cid),
            "subtitle": cfg.get("subtitle", ""),
            "source": cfg.get("source", ""),
        }
    return meta


def _build_row(
    row_def: dict[str, Any],
    charts_dir: Path,
    chart_meta: dict[str, dict[str, str]],
    available: set[str],
) -> Images | Image | None:
    """Build an Images or Image content block for one row.

    Returns None if no charts in the row are available.
    """
    chart_ids = row_def["charts"]
    present = [cid for cid in chart_ids if cid in available]
    if not present:
        return None

    if len(present) == 1:
        cid = present[0]
        meta = chart_meta.get(cid, {})
        return Image(
            file=charts_dir / f"{cid}.png",
            title=meta.get("title", cid),
            subtitle=meta.get("subtitle", ""),
            width=5,
        )

    images: dict[str, Image] = {}
    for cid in present:
        meta = chart_meta.get(cid, {})
        img = Image(
            file=charts_dir / f"{cid}.png",
            title=meta.get("title", cid),
            subtitle=meta.get("subtitle", ""),
            width=3,
        )
        images[f"{cid}.png"] = img

    return Images(
        id="row",
        images=list(images.values()),
        title="",
        subtitle="",
        width=3,
    )


def _build_section(
    section_title: str,
    rows: list[dict[str, Any]],
    charts_dir: Path,
    chart_meta: dict[str, dict[str, str]],
    available: set[str],
) -> Section | None:
    """Build a Section with chart rows."""
    contents: dict[str, Any] = {}
    idx = 0
    for row_def in rows:
        block = _build_row(row_def, charts_dir, chart_meta, available)
        if block is not None:
            contents[f"row_{idx}"] = block
            source_text = row_def.get("source", "")
            if source_text:
                contents[f"source_{idx}"] = Text(text=source_text)
            idx += 1

    if not contents:
        return None

    return Section(
        id=section_title.lower().replace(" ", "_"),
        title=section_title,
        contents=contents,
    )


def generate_report(
    charts_dir: Path,
    config_path: Path,
    output_path: Path,
) -> None:
    """Generate the Word document.

    Parameters
    ----------
    charts_dir
        Directory containing generated PNG files.
    config_path
        Path to charts.yaml (for titles/subtitles).
    output_path
        Path for the output .docx file.
    """
    chart_meta = _load_chart_meta(config_path)

    # Discover which charts were actually generated.
    available = {p.stem for p in charts_dir.glob("*.png")}
    logger.info("Report: %d charts available", len(available))

    # Build report structure.
    sections: dict[str, Any] = {}

    title = Title(
        title="Situacion Financiera de los Hogares",
        comment="",
    )
    sections["title"] = title

    section_defs = [
        ("Cuentas financieras", _SECTION_CUENTAS_FINANCIERAS),
        ("Credito a hogares", _SECTION_CREDITO),
        ("Tipos de interes", _SECTION_TIPOS),
    ]

    for section_title, rows in section_defs:
        section = _build_section(
            section_title,
            rows,
            charts_dir,
            chart_meta,
            available,
        )
        if section is not None:
            key = section_title.lower().replace(" ", "_")
            sections[key] = section

    report = Report(
        title="Situacion Financiera de los Hogares",
        contents=sections,
    )

    doc = Document()
    doc = report.render(doc)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))
    logger.info("Report saved: %s", output_path)
